spring.application.name=budget-backend
server.port=8080

# e.g. your-project-id
app.firebase.project-id=${FIREBASE_PROJECT_ID:}

# comma separated list for CORS
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}
